import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import { ThemeProvider } from "@/context/ThemeContext"
import DarkModeWelcomePopup from "@/components/DarkModeWelcomePopup"

const inter = Inter({ subsets: ["latin"] })

// Render every route dynamically so the HTML document is served with
// `Cache-Control: no-store` (Next.js emits this for dynamic routes). This
// guarantees browsers never show a stale page after a deploy without a hard
// refresh. Next.js hardcodes a cacheable header on statically-prerendered
// pages and ignores any override from middleware or next.config.js, so
// dynamic rendering is the only reliable way to get no-store. Hashed assets
// under /_next/static keep their long-lived immutable cache.
export const dynamic = "force-dynamic"

export const metadata: Metadata = {
  title: "Home | Pitt CS Wiki",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const theme = localStorage.getItem('theme') || 'dark';
                  if (theme === 'dark') {
                    document.documentElement.classList.add('dark');
                  } else {
                    document.documentElement.classList.remove('dark');
                  }
                } catch (e) {
                  console.error('Failed to initialize theme:', e);
                }
              })();
            `,
          }}
        />
      </head>
      <body className={inter.className}>
        <ThemeProvider>
          <Header />
          <DarkModeWelcomePopup />
          <div className="lg:w-[80vw] mx-auto container px-2">{children}</div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
